# baseURL = "http://www.zsney.com/"
baseURL = "https://zsney.netlify.com/"
languageCode = "en-us"
title = "Lucky Zhou's Blog"
theme = "hugo_theme_beg"

####################################
# For syntax hightlight style theme
####################################
# pygmentsUseClassic = true
# pygmentsStyle = "github"

[permalinks]
  post = "/blog/:year/:month/:day/:title/"
  top = "/:filename/"

###################### Theme config
[params]
  favicon = "/images/favicon.ico"
  hasBrandImage = true
  brandImage = "/images/brand_logo.jpg"
  brandImageAlt = "Lucky Zhou"

## Menu settings
[[menu.aboutme]]
  name = "About Me"
  url = "/about/"

[[menu.lifeline]]
  name = "Life Line"
  url = "/about/"




