# baseURL = "http://www.zsney.com/"
baseURL = "https://zsney.netlify.com/"
languageCode = "en-us"
title = "Lucky Zhou"
theme = "hugo_theme_beg"
disqusShortname = "zsney"

staticDir = ["static", "content_static"]

####################################
# For syntax hightlight style theme
####################################
# pygmentsUseClassic = true
# pygmentsStyle = "github"

[permalinks]
  post = "/blog/:year/:month/:day/:title/"
  top = "/:filename/"

###################### Theme config
[params]
  favicon = "/images/favicon.ico"
  hasBrandImage = true
  brandImage = "/images/brand_logo.jpg"
  brandImageAlt = "Lucky Zhou"
  github = "zslucky"
  facebook = "zsney.lzhou"
  wechat = "Zsney88"
  wechatQrcode = "/images/wechat_qrcode.jpeg"
  google = "zsney.lzhou@gmail.com"
  qq = "444950680"
  name = "Lucky Zhou"
  bio = "<p>I love open source world, I'm a senior Java and Frontend engineer, also a junior AI engineer. I'm reading Master degree of Finance, I want to explore some interesting things with AI and Finance.</p><p>If you are interested with me or any suggestion for me. don't hesitated to contact me!</p>"

  custom_css = ["css/font.css", "css/main.css"]

## Menu settings
[[menu.aboutme]]
  name = "About Me"
  pre = "<i class='fa fa-heart'></i>"
  url = "/about/"

# [[menu.lifeline]]
#   name = "Life Line"
#   url = "/about/"




